spring:
  data:
    elasticsearch:
      clustername: ${ES_CLUSTERNAME:sailfish}
      properties:
        host: ${ES_HOST:elasticsearch}
        port: ${ES_PORT:9300}
        poll: ${ES_POLL:600000ms}
    mongodb:
      uri: ${MONBODB_URI:mongodb://mongodb:27017/sailfish}
      repositories.enabled: false
    redis:
      repositories.enabled: false
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    pool:
      max-active: ${REDIS_POOL_MAX_ACTIVE:100}
      max-idle: ${REDIS_POOL_MAX_IDLE:8}
      max-wait: ${REDIS_POOL_MAX_WAIT:60000}
  sleuth:
    sampler:
      percentage: ${SLEUTH_SAMPLER:1.0}

eureka:
  client:
    register-with-eureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_SERVICE_URL:http://eureka/eureka/}

hystrix.command.default.execution.timeout.enabled: false
