server:
  port: 8080

info:
  app:
    version: dev-snapshot

gateway:
  version: dev-snapshot
  oauth2CheckTokenUrl: http://127.0.0.1:9999/oauth/check_token

spring:
  data:
    elasticsearch:
      clustername: sailfish
      properties:
        host: localhost
        port: 9300
        poll: 60000ms
    mongodb:
      uri: "mongodb://localhost:27017/sailfish"
      repositories.enabled: false
  redis:
    host: localhost
    port: 6379
    repositories.enabled: false
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    register-with-eureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://127.0.0.1:8761/eureka/"

hystrix.command.default.execution.timeout.enabled: false

logging:
  level:
    root: WARN
    io.picos: WARN
    com.netflix.zuul: WARN
