server:
  port: 80

security:
  basic:
    enabled: false

gateway:
  oauth2CheckTokenUrl: ${OAUTH2_CHECK_TOKEN_URL:http://oauth2/oauth/check_token}
  oauth2ClientId: ${OAUTH2_CLIENT_ID:gateway}
  oauth2ClientSecret: ${OAUTH2_CLIENT_SECRET:gateway-secret}
  enableAuthorize: ${GATEWAY_ENABLE_AUTHORIZE:true}
  enableCors: ${GATEWAY_ENABLE_CORS:false}
  corsAllowedOrigin: ${GATEWAY_CORS_ALLOWED_ORIGIN:*}
  tokenChangedChannel: ${GATEWAY_TOKEN_CHANGED_CHANNEL:cip_token_changed}
  userChangedChannel: ${GATEWAY_USER_CHANGED_CHANNEL:cip_user_changed}

spring:
  profiles:
    active: production


